# Generated by Django 3.2.dev20200731093317 on 2020-09-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='Edited',
            field=models.CharField(choices=[('wip', 'Work In Progress'), ('fin', 'Finished')], default='wip', max_length=20),
        ),
    ]
