# Generated by Django 3.2.dev20200731093317 on 2020-09-04 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_day_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='Last_Edit_Time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
