# Generated by Django 3.2.dev20200731093317 on 2020-09-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_day_last_edit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='Slug',
            field=models.SlugField(default='default-slug', max_length=100, unique_for_date='Last_Edit_Time'),
        ),
    ]
