# Generated by Django 3.2.dev20200731093317 on 2020-09-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_day_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('-Edited',)},
        ),
    ]
