# Generated by Django 3.2.dev20200731093317 on 2020-09-04 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_alter_day_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='day',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
