# Generated by Django 3.2.dev20200731093317 on 2020-09-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20200904_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='Slug',
            new_name='slug',
        ),
    ]
