# Generated by Django 3.2.dev20200731093317 on 2020-09-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_rename_slug_day_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('-Last_Edit_Time',)},
        ),
        migrations.RenameField(
            model_name='day',
            old_name='slug',
            new_name='Slug',
        ),
        migrations.RemoveField(
            model_name='day',
            name='publish',
        ),
    ]
