# Generated by Django 3.2.dev20200731093317 on 2020-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20200904_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='Edited',
        ),
        migrations.AddField(
            model_name='day',
            name='Privacy',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20),
        ),
    ]
