# Generated by Django 3.2.dev20200731093317 on 2020-09-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20200904_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='Slug',
            field=models.SlugField(max_length=100, unique_for_date='Last_Edit_Time'),
        ),
    ]
